server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
jwt:
  pubKeyPath: E:\ideaWorkspase\12-191125\zcc\myOwn\java\rsa\rsa.pub
  priKeyPath: E:\ideaWorkspase\12-191125\zcc\myOwn\java\rsa\rsa.pri
  secret: hjfkheuio144sdfa@#sda
  expire: 240
  cookieName: GMALL-TOKEN
  unick: unick